(()=>{
const PROVIDERS={openai:{name:'GPT',model:'gpt-5.6-luna',badge:'GPT'},deepseek:{name:'DeepSeek',model:'deepseek-v4-flash',badge:'DS'},kimi:{name:'Kimi',model:'kimi-k3',badge:'KIMI'}};
const PROVIDER_KEY='priority-desk-model-provider-v1';let provider=localStorage.getItem(PROVIDER_KEY)||'openai',pendingId=null;
document.body.insertAdjacentHTML('beforeend',`<section class="assistant-panel" id="assistantPanel"><div class="assistant-tools"><select id="assistantTask" title="选择便签任务"></select><select id="assistantProvider" title="选择回答模型">${Object.entries(PROVIDERS).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('')}</select><button id="assistantGear" title="保存此模型的 API Key">⚙</button></div><div class="assistant-response" id="assistantResponse"></div><form class="assistant-input" id="assistantForm"><input id="assistantPrompt" maxlength="300" placeholder="围绕任务问一句…" autocomplete="off"><button title="发送">↑</button></form><div class="assistant-settings" id="assistantSettings"><input id="assistantKey" type="password" placeholder="API Key（仅存本机）" autocomplete="off"><button id="assistantSaveKey" type="button">存</button><small>密钥保存到 macOS 钥匙串；聊天历史保存在本机。</small></div></section><span class="model-badge" id="modelBadge"></span>`);
const q=s=>document.querySelector(s),panel=q('#assistantPanel'),taskSelect=q('#assistantTask'),providerSelect=q('#assistantProvider'),response=q('#assistantResponse'),prompt=q('#assistantPrompt'),settings=q('#assistantSettings'),badge=q('#modelBadge');providerSelect.value=provider;
function applyProvider(){document.body.classList.remove('provider-openai','provider-deepseek','provider-kimi');document.body.classList.add(`provider-${provider}`);badge.textContent=PROVIDERS[provider].badge;providerSelect.value=provider}
window.renderAssistant=(top,visibleTasks=[])=>{let selected=taskSelect.value;taskSelect.innerHTML=visibleTasks.map(t=>`<option value="${t.id}">${esc(t.text)}</option>`).join('');if(visibleTasks.some(t=>t.id===selected))taskSelect.value=selected;else if(top)taskSelect.value=top.id;applyProvider()};
providerSelect.onchange=()=>{provider=providerSelect.value;pendingId=null;response.textContent='';document.body.classList.remove('assistant-busy','assistant-speaking');localStorage.setItem(PROVIDER_KEY,provider);settings.classList.remove('open');applyProvider()};
q('#assistantGear').onclick=()=>{settings.classList.toggle('open');q('#assistantKey').value='';q('#assistantKey').focus()};
q('#assistantSaveKey').onclick=()=>{let key=q('#assistantKey').value.trim();if(!key)return;window.webkit?.messageHandlers?.secret?.postMessage({provider,key});q('#assistantKey').value='';settings.classList.remove('open');response.textContent='密钥已保存到本机钥匙串'};
q('#assistantForm').onsubmit=e=>{e.preventDefault();let text=prompt.value.trim(),task=tasks.find(t=>t.id===taskSelect.value);if(!text||!task)return;pendingId=crypto.randomUUID();document.body.classList.add('assistant-busy');response.textContent='正在想';window.webkit?.messageHandlers?.model?.postMessage({id:pendingId,provider,model:PROVIDERS[provider].model,prompt:text,task:task.text});prompt.value=''};
window.onModelResult=result=>{if(result.id!==pendingId)return;document.body.classList.remove('assistant-busy');response.textContent=result.ok?result.text:(result.code==='MISSING_KEY'?'请先点齿轮保存这个模型的 API Key':result.error||'暂时无法回答');if(result.ok){document.body.classList.add('assistant-speaking');setTimeout(()=>document.body.classList.remove('assistant-speaking'),1800)}};
document.addEventListener('click',e=>{if(!e.target.closest('#assistantSettings,#assistantGear'))settings.classList.remove('open')});applyProvider();render();
})();
